# Generated by Django 3.1.6 on 2021-02-25 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210224_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dw2u3eucc/image/upload/v1614277176/fiverrClone/no_avatar_bb7wir.jpg', max_length=255, verbose_name='image'),
        ),
    ]
