# Generated by Django 3.1.6 on 2021-02-19 14:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='IR', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default=' ', verbose_name='long description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='short_bio',
            field=models.CharField(default=' ', max_length=35, verbose_name='write short bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
