# Generated by Django 3.1.6 on 2021-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_auto_20210221_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
