# Generated by Django 3.1.6 on 2021-02-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_auto_20210221_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
