# Generated by Django 3.1.6 on 2021-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_auto_20210222_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
