# Generated by Django 3.1.6 on 2021-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_auto_20210223_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='orderedTime',
            field=models.IntegerField(default=0),
        ),
    ]
