# Generated by Django 3.1.6 on 2021-02-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0010_gig_orderedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='orderedTime',
            new_name='quantity',
        ),
    ]
