# Generated by Django 3.1.6 on 2021-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_auto_20210223_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
