# Generated by Django 3.1.6 on 2021-02-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_auto_20210224_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
