# Generated by Django 3.1.6 on 2021-02-25 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_auto_20210224_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
